openapi: 3.1.0
info:
  version: 1.0.0
  title: federation et collectivite agricole
  description: digitalisation dans le domaine agricole

servers:
  - url: http://localhost:8080

paths:
  /collectivite:
    post:
      summary: creation d'une collectivite agricole
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CollectiviteAgricole'
      responses:
        '201':
          description: Collectivite creee avec succes
        '400':
          description: parametre invalide

components:
  schemas:
    membre:
      type: object
      properties:
        id:
          type: integer
        nomPrenom:
          type: string
        dateNaissance:
          type: string
          format: date-time
        adress:
          type: string
        metierExerce:
          type: string
        telephone:
          type: string
        adressEmail:
          type: string
        dateAdhesion:
          type: string
          format: date-time
        poste:
          type: string
          enum:
            - président
            - président adjoint
            - trésorier
            - secrétaire
            - membre confirmé
            - membre junior

    CollectiviteAgricole:
      type: object
      properties:
        id:
          type: integer
        nom:
          type: string
        specialite:
          type: string
        dateCreation:
          type: string
          format: date-time
        membres:
          type: array
          items:
            $ref: '#/components/schemas/membre'
        ville:
          type: string
        autorisation:
          type: boolean
      example:
        id: 3
        nom: "Cooperative Rizicole d'Ambatondrazaka"
        specialite: "Culture du riz"
        dateCreation: "2015-03-10T00:00:00Z"
        membres:
          - id: 1
            nomPrenom: "Rakoto Jean"
            dateNaissance: "1980-03-15T00:00:00Z"
            adress: "Antananarivo"
            metierExerce: "Agriculteur"
            telephone: "+261341234567"
            adressEmail: "rakoto.jean@example.com"
            dateAdhesion: "2023-06-01T00:00:00Z"
            poste: "président"
        ville: "Antananarivo"
        autorisation: true